<?php defined('PREVENT_DIRECT_ACCESS') OR exit('No direct script access allowed'); ?>
<?php $editing = isset($product['id']); ?>
<form method="post" data-product-form action="<?= site_url($editing ? 'products/update/' . (int) $product['id'] : 'products') ?>">
    <div class="form-grid">
        <label class="field field-wide"><span class="label">Product name</span><input class="input" type="text" name="product_name" maxlength="100" value="<?= htmlspecialchars((string) $product['product_name'], ENT_QUOTES, 'UTF-8') ?>" required><?= !empty($errors['product_name']) ? '<span class="error-text">' . htmlspecialchars($errors['product_name'], ENT_QUOTES, 'UTF-8') . '</span>' : '' ?></label>
        <label class="field field-wide"><span class="label">Description</span><textarea class="textarea" name="description" required><?= htmlspecialchars((string) $product['description'], ENT_QUOTES, 'UTF-8') ?></textarea><?= !empty($errors['description']) ? '<span class="error-text">' . htmlspecialchars($errors['description'], ENT_QUOTES, 'UTF-8') . '</span>' : '' ?></label>
        <label class="field"><span class="label">Price <span class="hint">(PHP)</span></span><span class="input-wrap has-prefix"><span class="input-prefix" aria-hidden="true">₱</span><input class="input" type="number" name="price" min="0" step="0.01" value="<?= htmlspecialchars((string) $product['price'], ENT_QUOTES, 'UTF-8') ?>" required></span><?= !empty($errors['price']) ? '<span class="error-text">' . htmlspecialchars($errors['price'], ENT_QUOTES, 'UTF-8') . '</span>' : '' ?></label>
        <label class="field"><span class="label">Quantity</span><input class="input" type="number" name="quantity" min="0" step="1" value="<?= htmlspecialchars((string) $product['quantity'], ENT_QUOTES, 'UTF-8') ?>" required><?= !empty($errors['quantity']) ? '<span class="error-text">' . htmlspecialchars($errors['quantity'], ENT_QUOTES, 'UTF-8') . '</span>' : '' ?></label>
    </div>
    <div class="form-actions"><a class="btn btn-secondary" href="<?= site_url('products') ?>">Cancel</a><button class="btn btn-primary" type="submit"><svg aria-hidden="true"><use href="#<?= $editing ? 'i-pencil' : 'i-plus' ?>"/></svg><?= $editing ? 'Save changes' : 'Create product' ?></button></div>
</form>